export const REQUEST_TYPES = {
  // 단일 리소스
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  REQUEST_EXTRA_ACTION: 'REQUEST_EXTRA_ACTION',
  // 복수 리소스
  BULK_CREATE: 'BULK_CREATE',
  BULK_READ: 'BULK_READ',
  BULK_UPDATE: 'BULK_UPDATE',
  BULK_DELETE: 'BULK_DELETE',
  BULK_REQUEST_EXTRA_ACTION: 'BULK_REQUEST_EXTRA_ACTION',
  // 리소스 수치(stats) 요청
  FETCH_STATS: 'FETCH_STATS',
};
