version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20

executors:
  api_server_exec:
    docker:
      - image: circleci/node:12.16.1
    environment:
      TZ: Asia/Seoul

jobs:

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Test
            mkdir -p ~/reports
            # test script

  build:
    executor: api_server_exec
    steps:
      - checkout
      - run:
          name: Install
          command: |
            echo yarn install
            yarn install
      - run:
          name: Test
          command: |
            echo yarn test
            #yarn test
      #- store_test_results:
      #    path: ~/reports
      #- store_artifacts:
      #    path: ~/reports
      - run:
          name: Build
          command: |
            echo yarn build:dev
            yarn build:dev
      - persist_to_workspace:
          root: ~/project
          paths:
            - script

  deploy-cdn-dev:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to dev envionment
          command: |
            echo deploy to dev envionment
            cd ./script && ./deploy-dev.sh

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - test
      - build
      - deploy-cdn-dev:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
