version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20

executors:
  api_server_exec:
    docker:
      - image: circleci/node:12.14.1
    environment:
      TZ: Asia/Seoul

jobs:

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Test
            mkdir -p ~/reports
            # test script

  build:
    executor: api_server_exec
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: DEV_AWS_ACCESS_KEY_ID
          aws-secret-access-key: DEV_AWS_SECRET_ACCESS_KEY
          aws-region: DEV_AWS_DEFAULT_REGION
      - run:
          name: Install
          command: |
            echo yarn install
            yarn install
      - run:
          name: Test
          command: |
            echo yarn test
            #yarn test
      #- store_test_results:
      #    path: ~/reports
      #- store_artifacts:
      #    path: ~/reports
      - run:
          name: Build
          command: |
            echo yarn build:dev
            yarn build:dev
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  deploy-cdn-dev:
    executor: api_server_exec
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to dev envionment
          environment:
            BUILD_DIR: build
            S3_BUCKET: s3://biz-corp-admin.dev.platdev.net
            CDN_ID: E1SAL9QNUQW32T
          command: |
            echo deploy to dev envionment
            # Sync the bundle project
            aws s3 sync $BUILD_DIR $S3_BUCKET --acl public-read
            # Clear the cache
            aws cloudfront create-invalidation --distribution-id $CDN_ID --paths /index.html /favicon.ico

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - test
      - build
      - deploy-cdn-dev:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
