version: 2.1

executors:
  api_server_exec:
    docker:
      # Primary container
      - image: circleci/node:12.14.1
    environment:
      TZ: Asia/Seoul
      NODE_ENV: test

jobs:
  build:
    #executor: api_server_exec
    machine: true
    steps:
      - checkout
      #- run:
      #    name: Migrate Database
      #    command: yarn run migrate
      - run:
          name: Build
          command: |
            echo Build
            mkdir -p ~/reports
            # test script
      #- store_test_results:
      #    path: ~/reports
      #- store_artifacts:
      #    path: ~/reports

  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Test
            mkdir -p ~/reports
            # test script
      #- store_test_results:
      #    path: ~/reports
      #- store_artifacts:
      #    path: ~/reports

  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to the Development Environment
          command: |
            echo deploy to dev envionment
            cd ./script && ./deploy-dev.sh

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy-dev:
          requires:
            - build
            - test
          filters:
            branches:
              only: develop
